### ISSUE TITLE
upgrade gcc version to gcc12

### ISSUE THREAD

**Issue by BiteTheDDDDt** [amosbird/ldb_toolchain_gen#19]
gcc12 has been released and updated several minor versions.
Maybe we can upgrade the gcc version in ldb toolchain?

**Comment by amosbird** [comment]
IIRC there is no gcc-12 available for ubuntu-18/20 (I used this PPA https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). The main idea behind `ldb_toolchain` is to use the pre-built toolchains from famous linux distributions, instead of bootstrapping from scratch, see https://github.com/amosbird/ldb_toolchain_gen#introduction.

Unfortunately we cannot upgrade to ubuntu-22 or newer because glibc-compatibility will fail to work after GLIBC 2.34 (Starting from 2.34 we will require a new __libc_main_start which is basically impossible to patch.)
